---
title: "All Together"
subtitle: "Part I"
author: "Fernando Hoces la Guardia"
date: "08/8/2022"
output: 
  xaringan::moon_reader:
    footer: "These slides available at https://fhoces.github.io/econ140summer2022/"
    css: [default, metropolis, metropolis-fonts, "my-css.css"] 
    lib_dir: libs
    nature:
      ratio: '16:9'
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
editor_options: 
  chunk_output_type: console
---

<style type="text/css">
.remark-slide-content {
    font-size: 30px;
    padding: 1em 1em 1em 1em;
}
</style>

```{r , include = F}
options(htmltools.dir.version = FALSE)
library(pacman)
p_load(ggthemes, viridis, knitr, extrafont, tidyverse, magrittr, latex2exp, 
       parallel, Ecdat, wooldridge, dslabs, ggforce, emo, png, grid, pander, 
       countdown, emoGG, haven, broom, ggridges, gridExtra, kableExtra, snakecase, 
       janitor, data.table, lubridate, lfe, here, gapminder, AER, stargazer, margins, 
       furrr)


# Define pink color
red_pink <- "#e64173"
turquoise <- "#20B2AA"
orange <- "#FFA500"
red <- "#fb6107"
blue <- "#3b3b9a"
green <- "#8bb174"
grey_light <- "grey70"
grey_mid <- "grey50"
grey_dark <- "grey20"
purple <- "#6A5ACD"
slate <- "#314f4f"
# Dark slate grey: #314f4f

options(htmltools.dir.version = FALSE)

# define vars
om = par("mar")
lowtop = c(om[1],om[2],0.1,om[4])

overwrite = FALSE


# Define colors
red_pink <- "#e64173"
met_slate <- "#23373b" # metropolis font color
# Notes directory
# Knitr options
opts_chunk$set(
  comment = "#>",
  fig.align = "center",
  fig.height = 7,
  fig.width = 10.5,
  #dpi = 300,
  #cache = T,
  message = FALSE,
  warning = FALSE,
  dev = "svg",
  cache = TRUE
  #fig.width = 11,
  #fig.height = 5
)

theme_simple <- theme_bw() + theme(
  axis.line = element_line(color = met_slate),
  panel.grid = element_blank(),
  rect = element_blank(),
  strip.text = element_blank(),
  text = element_text(family = "Fira Sans", color = met_slate, size = 14),
  axis.text.x = element_text(size = 12),
  axis.text.y = element_text(size = 12),
  axis.ticks = element_blank(),
  plot.title = element_blank(),
  legend.position = "none"
)
theme_empty <- theme_bw() + theme(
  line = element_blank(),
  rect = element_blank(),
  strip.text = element_blank(),
  axis.text = element_blank(),
  plot.title = element_blank(),
  axis.title = element_blank(),
  plot.margin = structure(c(0, 0, -0.5, -1), unit = "lines", valid.unit = 3L, class = "unit"),
  legend.position = "none"
)
theme_simple <- theme_bw() + theme(
  line = element_blank(),
  panel.grid = element_blank(),
  rect = element_blank(),
  strip.text = element_blank(),
  axis.text.x = element_text(size = 18, family = "STIXGeneral"),
  axis.text.y = element_blank(),
  axis.ticks = element_blank(),
  plot.title = element_blank(),
  axis.title = element_blank(),
  # plot.margin = structure(c(0, 0, -1, -1), unit = "lines", valid.unit = 3L, class = "unit"),
  legend.position = "none"
)
theme_axes_math <- theme_void() + theme(
  text = element_text(family = "MathJax_Math"),
  axis.title = element_text(size = 22),
  axis.title.x = element_text(hjust = .95, margin = margin(0.15, 0, 0, 0, unit = "lines")),
  axis.title.y = element_text(vjust = .95, margin = margin(0, 0.15, 0, 0, unit = "lines")),
  axis.line = element_line(
    color = "grey70",
    size = 0.25,
    arrow = arrow(angle = 30, length = unit(0.15, "inches")
  )),
  plot.margin = structure(c(1, 0, 1, 0), unit = "lines", valid.unit = 3L, class = "unit"),
  legend.position = "none"
)
theme_axes_serif <- theme_void() + theme(
  text = element_text(family = "MathJax_Main"),
  axis.title = element_text(size = 22),
  axis.title.x = element_text(hjust = .95, margin = margin(0.15, 0, 0, 0, unit = "lines")),
  axis.title.y = element_text(vjust = .95, margin = margin(0, 0.15, 0, 0, unit = "lines")),
  axis.line = element_line(
    color = "grey70",
    size = 0.25,
    arrow = arrow(angle = 30, length = unit(0.15, "inches")
  )),
  plot.margin = structure(c(1, 0, 1, 0), unit = "lines", valid.unit = 3L, class = "unit"),
  legend.position = "none"
)
theme_axes <- theme_void() + theme(
  text = element_text(family = "Fira Sans Book"),
  axis.title = element_text(size = 18),
  axis.title.x = element_text(hjust = .95, margin = margin(0.15, 0, 0, 0, unit = "lines")),
  axis.title.y = element_text(vjust = .95, margin = margin(0, 0.15, 0, 0, unit = "lines")),
  axis.line = element_line(
    color = grey_light,
    size = 0.25,
    arrow = arrow(angle = 30, length = unit(0.15, "inches")
  )),
  plot.margin = structure(c(1, 0, 1, 0), unit = "lines", valid.unit = 3L, class = "unit"),
  legend.position = "none"
)
theme_set(theme_gray(base_size = 20))
# Column names for regression results
reg_columns <- c("Term", "Est.", "S.E.", "t stat.", "p-Value")
# Function for formatting p values
format_pvi <- function(pv) {
  return(ifelse(
    pv < 0.0001,
    "<0.0001",
    round(pv, 4) %>% format(scientific = F)
  ))
}
format_pv <- function(pvs) lapply(X = pvs, FUN = format_pvi) %>% unlist()
# Tidy regression results table
tidy_table <- function(x, terms, highlight_row = 1, highlight_color = "black", highlight_bold = T, digits = c(NA, 3, 3, 2, 5), title = NULL) {
  x %>%
    tidy() %>%
    select(1:5) %>%
    mutate(
      term = terms,
      p.value = p.value %>% format_pv()
    ) %>%
    kable(
      col.names = reg_columns,
      escape = F,
      digits = digits,
      caption = title
    ) %>%
    kable_styling(font_size = 20) %>%
    row_spec(1:nrow(tidy(x)), background = "white") %>%
    row_spec(highlight_row, bold = highlight_bold, color = highlight_color)
}


```



```{css, echo = F, eval = T}
@media print {
  .has-continuation {
    display: block !important;
  }
}
```


# Data

.font110[
```{r, echo=FALSE, eval=TRUE}
data(wage1)

df <- data.frame("pot_out_oc_0" = c( rep("A", 8) , rep("B", 2) ), 
                 "pot_out_oc_1" = c( rep("A", 2) , rep("B", 8) ),
                 "pot_out_w_0" = c( rep(1, 2) , rep(0, 6), rep(4, 2)), 
                 "pot_out_w_1" = c( rep(1, 2) , rep(2, 6), rep(4, 2)))

df <- df %>% mutate("indiv_te" = pot_out_w_1 - pot_out_w_0, 
              "treat" = rep(c(0,1), 5), 
              "ocup" = if_else(treat == 1, pot_out_oc_1, pot_out_oc_0),
              "wage" = if_else(treat == 1, pot_out_w_1, pot_out_w_0))
      
wage1 <- select(wage1, wage, educ, tenure, female, nonwhite) %>%
  mutate(wage = round(wage, 2))
DT::datatable(
  df,
  colnames = c(
    '<span style="color: #007935 !important">\\(Y^{oc}_{i0}\\)</span>',
    '<span style="color: #007935 !important">\\(Y^{oc}_{i1}\\)</span>',
    '<span style="color: #007935 !important">\\(Y^{w}_{i0}\\)</span>',
    '<span style="color: #007935 !important">\\(Y^{w}_{i1}\\)</span>', 
    '<span style="color: #007935 !important">\\(TE_{i}\\)</span>',
    '<span style="color: #007935 !important">\\(Treat\\)</span>', 
    '<span style="color: #007935 !important">\\(Y^{oc}_{i}\\)</span>', 
    '<span style="color: #007935 !important">\\(Y^{w}_{i}\\)</span>'
  ), 
  fillContainer = FALSE, options = list(pageLength = 3,
                                       lengthChange = FALSE,
                                       searching = FALSE), escape = FALSE) %>% 
  DT::formatStyle(0, color = '#FD5F00')
```
]

---

# Data

.font100[
```{r, echo=FALSE, eval=TRUE}
data(wage1)

df <- data.frame("pot_out_oc_0" = c( rep("A", 8) , rep("B", 2) ), 
                 "pot_out_oc_1" = c( rep("A", 2) , rep("B", 8) ),
                 "pot_out_w_0" = c( rep(1, 2) , rep(0, 6), rep(4, 2)), 
                 "pot_out_w_1" = c( rep(1, 2) , rep(2, 6), rep(4, 2)))

df <- df %>% mutate("indiv_te" = pot_out_w_1 - pot_out_w_0, 
              "treat" = rep(c(0,1), 5), 
              "ocup" = if_else(treat == 1, pot_out_oc_1, pot_out_oc_0),
              "wage" = if_else(treat == 1, pot_out_w_1, pot_out_w_0))
      
wage1 <- select(wage1, wage, educ, tenure, female, nonwhite) %>%
  mutate(wage = round(wage, 2))
DT::datatable(
  df,
  colnames = c(
    '<span style="color: #007935 !important">\\(Y^{oc}_{i0}\\)</span>',
    '<span style="color: #007935 !important">\\(Y^{oc}_{i1}\\)</span>',
    '<span style="color: #007935 !important">\\(Y^{w}_{i0}\\)</span>',
    '<span style="color: #007935 !important">\\(Y^{w}_{i1}\\)</span>', 
    '<span style="color: #007935 !important">\\(TE_{i}\\)</span>',
    '<span style="color: #007935 !important">\\(Treat\\)</span>', 
    '<span style="color: #007935 !important">\\(Y^{oc}_{i}\\)</span>', 
    '<span style="color: #007935 !important">\\(Y^{w}_{i}\\)</span>'
  ), 
  fillContainer = FALSE, options = list(pageLength = 10,
                                       lengthChange = FALSE,
                                       searching = FALSE), escape = FALSE) %>% 
  DT::formatStyle(0, color = '#FD5F00')
```
]





---
# Data

.left-thin[
- asd
]


.right-wide[
.font70[
```{r, echo=FALSE, eval=TRUE}
data(wage1)

df <- data.frame("pot_out_oc_0" = c( rep("A", 8) , rep("B", 2) ), 
                 "pot_out_oc_1" = c( rep("A", 2) , rep("B", 8) ),
                 "pot_out_w_0" = c( rep(1, 2) , rep(0, 6), rep(4, 2)), 
                 "pot_out_w_1" = c( rep(1, 2) , rep(2, 6), rep(4, 2)))

df <- df %>% mutate("indiv_te" = pot_out_w_1 - pot_out_w_0, 
              "treat" = rep(c(0,1), 5), 
              "ocup" = if_else(treat == 1, pot_out_oc_1, pot_out_oc_0),
              "wage" = if_else(treat == 1, pot_out_w_1, pot_out_w_0))
      
wage1 <- select(wage1, wage, educ, tenure, female, nonwhite) %>%
  mutate(wage = round(wage, 2))
DT::datatable(
  df,
  colnames = c(
    '<span style="color: #007935 !important">\\(Y^{oc}_{i0}\\)</span>',
    '<span style="color: #007935 !important">\\(Y^{oc}_{i1}\\)</span>',
    '<span style="color: #007935 !important">\\(Y^{w}_{i0}\\)</span>',
    '<span style="color: #007935 !important">\\(Y^{w}_{i1}\\)</span>', 
    '<span style="color: #007935 !important">\\(TE_{i}\\)</span>',
    '<span style="color: #007935 !important">\\(Treat\\)</span>', 
    '<span style="color: #007935 !important">\\(Y^{oc}_{i}\\)</span>', 
    '<span style="color: #007935 !important">\\(Y^{w}_{i}\\)</span>'
  ), 
  fillContainer = FALSE, options = list(pageLength = 10,
                                       lengthChange = FALSE,
                                       searching = FALSE), escape = FALSE) %>% 
  DT::formatStyle(0, color = '#FD5F00')
```
]
]


---
# Acknowledgments

- MM


```{r gen_pdf, include = FALSE, cache = FALSE, eval = TRUE}
pagedown::chrome_print("24_dd_p2.html", output = "24_dd_p2.pdf")
```